name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SQLite
        run: apt install sqlite3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Create .env files
        run: |
          echo "DB_FILENAME=database.db" > .env
          echo "DB_FILENAME=test_database.db" > .env.test
          echo "SCHEMA_FILENAME=schema.sql" >> .env
          echo "SCHEMA_FILENAME=schema.sql" >> .env.test
      - name: Run pytest tests
        run: poetry run coverage run --branch -m pytest
        env:
          LD_LIBRARY_PATH: /usr/local/lib
      - name: Coverage report
        run: poetry run coverage xml
      - name: Coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Run robot tests
        run: |
          cd src
          poetry run flask run &
          poetry run robot tests
          cd ../
        env:
          LD_LIBRARY_PATH: /usr/local/lib
      - name: Lint
        run: poetry run pylint src

      - uses: actions/checkout@v2

