name: CI

on:
  push:
    branches: [main, db-connection-fix]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run pytest tests
        run: poetry run coverage run --branch -m pytest
      - name: Run robot tests
        run: |
           cd src
           poetry run flask run &
           poetry run robot tests
           cd ../
      - name: Coverage report
        run: |
           poetry run coverage html;
           poetry run coverage xml
      - name: Lint
        run: poetry run pylint src
